### ISSUE TITLE
Slack Education

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#3]
Get familiar with slack. Ask John, Dee, Petya and Jenny how they each manage (block out/get across) all of the channels.

**Comment by jennybeaumont** [comment]
My pro tips for personal management:
* Only join channels you need (you can always join more later, or leave channels)
* Mute channels as needed (you will still see notifications, but it's less noisy and distracting for little used channels, like #company-admin for example)
* Set up Do Not Disturb preferences
* Add keywords for any extra alerts (for example, we are 3 Jenny's in the company, so I don't won't pings for "Jenny", but some people call me "Beaumont", so I've set a keyword for that)
* Remember we are an async company, no pressure to answer messages instantaneously (and the flipside, folks might not answer you right away)
* You can set a status to show people when you're on the phone, AFK, etc to help set expectations on your availability
* Use reminders either to set up global reminders for whole channels, or as a personal reminder to revisit a particular message or question someone left you https://slack.com/intl/en-fr/help/articles/208423427-set-a-reminder

My pro tip for project management:
* Encourage people to communicate in open channels, avoid DMs as much as possible

Voilà ! hope that helps :)

**Comment by thewebprincess** [comment]
All of Jenny's points as well as the following:

- star the channels and/or users you connect with most often which pops them to the top of the channel list. I have all the PM team private channels, the PM channel, and project channels in there 
- Don't install it on your phone - or, don't turn notifications on your phone so that you drive Slack, not the reverse. It means keeping sensible boundaries with the clients in terms of access to you outside of work hours. But the incessant notifications can keep pulling you back in, so I've found that it's better to let you drive Slack and dip in when YOU want rather than indulge the pavlovian response to alerts from it.
- come and go from channels as you need them, don't feel like you have to stay in them - e.g. for me, I manage #company-admin in that I'll enter,  ask my question and leave when its resolved... 
- don't `@channel` or `@everyone` - it's a rookie mistake... and if you have to use group alerts, use`@here` sparingly - https://slack.com/intl/en-au/help/articles/202009646-Notify-a-channel-or-workspace or use a `@teampm` or an individual's handle.

**Comment by petyaraykovska** [comment]
Our handbook has a very good general rules of thumb around the expectation on using Slack at HM: I'd recommend starting with this first: https://handbook.hmn.md/working-here/communication/slack/ 

Another thing I find very useful: You have a personal Slack channel that's just yours - in the left column you'll find it under "Direct messages" labeled Corey (you). I use that for notes and for integrating my Github issues there. I've done a Github integration of all the issues that are assigned to me in all repos and also all the client services issues labeled "Allocations". It helps me keep on top of things I need to see and I get a notification in Slack every time I'm mentioned in a Github issue - that way I don't need email to keep on top of Github - just Slack.

**Comment by thewebprincess** [comment]
I love how everyone has a different way of using it! I use https://octobox.io for github notifications beause it lays out notifications like an email in box, but I can see how useful it would be having all the notifications in one place!
