### ISSUE TITLE
P2 Updates. How/What/Why

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#7]
Qu'est-ce que la P2!? Ask John. Assuming this access is through the HM site as well.

**Comment by petyaraykovska** [comment]
P2 is a name of a theme for WordPress which has as its main feature frontend editing. At HM some of our internal sites still use P2 (which is why you'll see it in most of our documentation that has been written 2+ years ago) but most sites these days use H2 - a newer theme which is an updated, better working version of P2 that we built internally. 

Both of them use frontend editing meaning you can create posts from the frontend of the site, comment, etc vs the standard WP functionality where you need to go to the backend and create posts there. H2 has better design, it's in the HM colours and has a bunch of small improvements as well. 

The P2s (H2s) you need access to are also listed in my comment in #5
